import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from "react";
import { CosmWasmClient } from '@cosmjs/cosmwasm-stargate';
import axios from "axios";
import { Gallery } from "../components/gallery";

const Home: NextPage = () => {
  const [tokenIds, setTokenIds] = useState<string[]>([]);

  useEffect(() => {
    //

    const animationUrl = 'https://ipfs.io/ipfs/bafybeif6urhfyqg546radpos4spy45rwv2rxzndhqxqvbhuyl3ui7hvwxm/%TOKEN_ID%';
    const imageUrl= 'ipfs://bafybeigrbiuatbqgeatfhfik6lzu6v4etqevrpvlp4d5rzl5salrhyso54/%TOKEN_ID%.jpg';

    (async ()=>{
// const acc1='stars1524hf3dmcl8lagnfhuct4k2002pv73yswnl9cf'
const acc2='stars1euu359d2cwe46j8a8fqkmcrhzjq6j642htt7rn'
      const client = await CosmWasmClient.connect('https://rpc.big-bang-1.stargaze-apis.com/');
      const sg721 = 'stars1msfmkx4xmts3el3r46c2u2eehxkhahqzsa0crn0v58cncp7ztr7qrshkkh';


let account =acc2;
        console.log(account)
        const balance = await client.getBalance(account, 'ustars');
        console.log(account,'account balance:', balance);

        const ownedTokens = await client.queryContractSmart(sg721,{ tokens: { owner:account }});
        console.log(account, 'owned tokens:', ownedTokens.tokens);
        const arr = ownedTokens.tokens as string[];
      setTokenIds(arr)
        // if(!arr){
        //   console.log(account, 'no tokens owned');
        //   continue;
        // }
        // const tokens = [];
        // let i=0;
        // for (let tokenId of arr) {
        //   const info = await client.queryContractSmart(sg721, { nft_info: { token_id: tokenId } })
        //   console.log('tokenId', info.token_uri)
        //   tokens[i++]= { token_id:tokenId , token_uri:info.token_uri as string }
        // }
        // for (let tokenInfo of tokens) {
        //   const metadata = tokenInfo.token_uri.replace('ipfs://','https://ipfs.io/ipfs/')
        //   const metadataRes = await axios.get(metadata);
        //   const url = metadataRes.data.animation_url;
        //   console.log(tokenInfo.token_id, 'animation_url', url)
        // }



      //stars1euu359d2cwe46j8a8fqkmcrhzjq6j642htt7rn
      //stars1524hf3dmcl8lagnfhuct4k2002pv73yswnl9cf
      // console.log(acc1, await client.getAllBalances('stars1524hf3dmcl8lagnfhuct4k2002pv73yswnl9cf'))
      // console.log(acc2,await client.getAllBalances(acc2))
      // client.
      // client.getAccount('stars1euu359d2cwe46j8a8fqkmcrhzjq6j642htt7rn').then(accounts => {
      //   console.log(accounts);
      // });
    })()

  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Hyperion Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hyperion Gallery
        </h1>

        {/*<iframe allow={"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture;"} allowFullScreen frameBorder={"0"}*/}
        {/*        height={"100%"} sandbox={"allow-scripts"} src={"https://hyperion.stewart.codes/gen/4/"} width={"100%"}*/}
        {/*        style={{ "min-height": "500px;" }}></iframe>*/}
<Gallery tokenIds={tokenIds}/>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
